---
title: "Best creators in Europe's top 5 leagues in 2020-2021"
date: '2020 11 14 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
library(ggrepel)
theme_set(theme_light())
```

```{r}
player_names <- read_html("https://fbref.com/en/comps/Big5/passing/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes("th+ .left a") %>% 
  html_text()

league <- read_html("https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".center~ .left+ .left") %>% 
  html_text()

xa <- read_html("https://fbref.com/en/comps/Big5/passing/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".right:nth-child(25)") %>% 
  html_text() %>% 
   as.numeric()


ninetees <- read_html("https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".center+ .right") %>% 
  html_text() %>% 
   as.numeric()

pass_live <- read_html("https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes("#stats_gca .right:nth-child(12)") %>% 
  html_text() %>% 
   as.numeric()

drib <- read_html("https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".right:nth-child(14)") %>% 
  html_text() %>% 
   as.numeric()

sh <- read_html("https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes("#stats_gca .right:nth-child(15)") %>% 
  html_text() %>% 
   as.numeric()

fld <- read_html("https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes("#stats_gca .right:nth-child(16)") %>% 
  html_text() %>% 
   as.numeric()

def <- read_html("https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes("#stats_gca .right:nth-child(17)") %>% 
  html_text() %>% 
   as.numeric()


```

```{r}
best_creators <- data.frame(player_names, xa, pass_live, ninetees, league, drib, sh, fld, def)

clean_best_creators <- best_creators %>% 
  mutate(league = str_remove_all(league, "eng"),
         league = str_remove_all(league, "de"),
         league = str_remove_all(league, "es"),
         league = str_remove_all(league, "it"),
         league = str_remove_all(league, "fr"),
         league = str_replace_all(league, "Bunsliga", "Bundesliga")) 
  
  

clean_best_creators2 <- clean_best_creators %>% 
  mutate(open_play_actions = (pass_live + drib + sh + fld + def) / ninetees) %>% 
  mutate(xa90 = xa / ninetees) 



clean_best_creators2 %>%
  top_n(100) %>% 
  filter(ninetees >= 8) %>% 
  ggplot(aes(open_play_actions, xa90, label = player_names)) +
  geom_point(aes(color = league, size = 0)) +
  guides(colour = guide_legend(override.aes = list(size=5))) +
  guides(size = FALSE) +
  geom_text_repel(aes(label=ifelse((xa90 > 0.3)|(open_play_actions > 3), player_names,''))) +
   labs(x = "Open play SCA per 90",
       y = "xA per 90",
       title = "Best creators in Europe's top 5 leagues in 2020-2021",
       subtitle = "Minimum 8 90s played", 
       caption = "data: fbref.com") +
 theme(panel.background = element_rect(fill = "#F8F9F9"),
          panel.border = element_blank(),
          panel.grid.major = element_line(color = "#ABB2B9"),
          panel.grid.minor = element_line(color = "#ABB2B9"),
          plot.background = element_rect(fill = "#F8F9F9"),
          legend.background = element_rect(fill="#F8F9F9"),
          legend.title=element_blank(),
          legend.key = element_rect(fill = "#F8F9F9"))

```
