---
title: "Top Five League Expected Goal Contributions 2020-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
library(rvest)
library(scales)
library(ggrepel) 
library(magick)
```

```{r}
npxg <- read_html("https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".right:nth-child(23)") %>% 
  html_text() %>% 
  as.numeric()
 
 xa <- read_html("https://fbref.com/en/comps/Big5/passing/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".right:nth-child(25)") %>% 
  html_text() %>% 
  as.numeric() 
 
   player_names <- read_html("https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes("th.right+ .left") %>% 
  html_text()
   
 league <- read_html("https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".center~ .left+ .left") %>% 
  html_text()
   
   
ninetees <- read_html("https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats") %>% 
  html_nodes(".center+ .right") %>% 
  html_text() %>% 
  as.numeric()
```

#Top 5 League

```{r}
fbref %>% 
  filter(ninetees >= 18) %>% 
  top_n(n = 15, w = npxg90) %>% 
  mutate(player_names = fct_reorder(player_names, npxg90)) %>%
  ggplot(aes(x = npxg90, y = player_names, fill = xa90)) +
  geom_col() +
  geom_text(aes(label = round(npxg90, 2)), nudge_x = -.020, color="white", hjust = 1) +
  scale_x_continuous(expand = expansion(mult = c(0, .1))) +
  scale_fill_gradient(low = 'gray60', high = 'gray8') +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank()) +
   labs(x = " ",
       y = " ",
       title = "Expected Goal Contributions In Top 5 League",
       subtitle = "minimum 18 90s played",
       caption = "data: fbref.com",
       fill = "xA/90")
```

#Bundesliga

```{r}
fbref %>% 
  filter(ninetees >= 18,
         str_detect(league, "Bundesliga")) %>%
  top_n(n = 15, w = npxg90) %>% 
  mutate(player_names = fct_reorder(player_names, npxg90)) %>%
  ggplot(aes(x = npxg90, y = player_names, fill = xa90)) +
  geom_col() +
  geom_text(aes(label = round(npxg90, 2)), nudge_x = -.020, color="white", hjust = 1) +
  scale_x_continuous(expand = expansion(mult = c(0, .1))) +
  scale_fill_gradient(low = 'deepskyblue', high = 'blue4') +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank()) +
   labs(x = " ",
       y = " ",
       title = "Bundesliga Expected Goal Contributions",
       subtitle = "minimum 18 90s played",
       caption = "data: fbref.com",
       fill = "xA/90")
```

#Premier League

```{r}
fbref %>% 
  filter(ninetees >= 18,
         str_detect(league, "Premier League")) %>%
  top_n(n = 15, w = npxg90) %>% 
  mutate(player_names = fct_reorder(player_names, npxg90)) %>%
  ggplot(aes(x = npxg90, y = player_names, fill = xa90)) +
  geom_col() +
  geom_text(aes(label = round(npxg90, 2)), nudge_x = -.020, color="white", hjust = 1) +
  scale_x_continuous(expand = expansion(mult = c(0, .1))) +
  scale_fill_gradient(low = 'mediumorchid1', high = 'mediumpurple4') +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank()) +
   labs(x = " ",
       y = " ",
       title = "Premier League Expected Contributions",
       subtitle = "minimum 18 90s played",
       caption = "data: fbref.com",
       fill = "xA/90")
```

#LaLiga

```{r}
fbref %>% 
  filter(ninetees >= 18,
         str_detect(league, "La Liga")) %>%
  top_n(n = 15, w = npxg90) %>% 
  mutate(player_names = fct_reorder(player_names, npxg90)) %>%
  ggplot(aes(x = npxg90, y = player_names, fill = xa90)) +
  geom_col() +
  geom_text(aes(label = round(npxg90, 2)), nudge_x = -.020, color="white", hjust = 1) +
  scale_x_continuous(expand = expansion(mult = c(0, .1))) +
  scale_fill_gradient(low = 'red', high = 'red4') +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank()) +
   labs(x = " ",
       y = " ",
       title = "La Liga Leaders Expected Goal Contributions",
       subtitle = "minimum 18 90s played",
       caption = "data: fbref.com",
       fill = "xA/90")
```

#Seria A

```{r}
fbref %>% 
  filter(ninetees >= 18,
         str_detect(league, "Serie A")) %>%
  top_n(n = 15, w = npxg90) %>% 
  mutate(player_names = fct_reorder(player_names, npxg90)) %>%
  ggplot(aes(x = npxg90, y = player_names, fill = xa90)) +
  geom_col() +
  geom_text(aes(label = round(npxg90, 2)), nudge_x = -.020, color="white", hjust = 1) +
  scale_x_continuous(expand = expansion(mult = c(0, .1))) +
  scale_fill_gradient(low = 'springgreen', high = 'springgreen4') +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank()) +
   labs(x = " ",
       y = " ",
       title = "Serie A Leaders Expected Goal Contributions",
       subtitle = "minimum 18 90s played",
       caption = "data: fbref.com",
       fill = "xA/90")
```

#League 1

```{r}
fbref %>% 
  filter(ninetees >= 18,
         str_detect(league, "Ligue 1")) %>%
  top_n(n = 15, w = npxg90) %>% 
  mutate(player_names = fct_reorder(player_names, npxg90)) %>%
  ggplot(aes(x = npxg90, y = player_names, fill = xa90)) +
  geom_col() +
  geom_text(aes(label = round(npxg90, 2)), nudge_x = -.020, color="white", hjust = 1) +
  scale_x_continuous(expand = expansion(mult = c(0, .1))) +
  scale_fill_gradient(low = 'limegreen', high = 'navyblue') +
  theme_light() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank()) +
   labs(x = " ",
       y = " ",
       title = "Ligue 1 Leaders Expected Goal Contributions",
       subtitle = "minimum 18 90s played",
       fill = "xA/90")
```

